In [35]:
import torch

# a = torch.tensor([1, 2, 3])
# b = torch.tensor([4, 5, 6])
labels = torch.tensor([1, 2])
a = torch.randn(2, 3)
b = torch.randn(2, 3)


In [36]:
mask = labels.unsqueeze(0) == labels.unsqueeze(1)

In [37]:
sim_matrix = torch.matmul(a, b.t()) 

In [38]:
f_pos = torch.diag(sim_matrix)

In [39]:
sim_matrix

tensor([[-0.6440,  1.5417],
        [ 0.8242, -1.9637]])

In [40]:
f_neg = sim_matrix*(~mask)

In [43]:
f_neg

tensor([[-0.0000, 1.5417],
        [0.8242, -0.0000]])

In [44]:
f_concat = torch.cat([f_pos.unsqueeze(1), f_neg], dim=1)

tensor([[-0.6440, -0.0000,  1.5417],
        [-1.9637,  0.8242, -0.0000]])

In [46]:
import torch.nn.functional as F

a_norm = F.normalize(a, p=2, dim=1)

In [47]:
a_norm

tensor([[-0.2399, -0.6426,  0.7277],
        [-0.6178,  0.6752,  0.4030]])